version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: queryvault
      POSTGRES_PASSWORD: queryvault@1234    
      POSTGRES_DB: queryvault        
    ports:
      - "5432:5432"                
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: